// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TriatlonProtocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Triatlon.Protocol {

  /// <summary>Holder for reflection information generated from TriatlonProtocol_v3.proto</summary>
  public static partial class TriatlonProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for TriatlonProtocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TriatlonProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlUcmlhdGxvblByb3RvY29sX3YzLnByb3RvEhF0cmlhdGxvbi5wcm90b2Nv",
            "bCJWCgdBcmJpdHJ1EgoKAmlkGAEgASgDEgwKBG51bWUYAiABKAkSDwoHcHJl",
            "bnVtZRgDIAEoCRIQCgh1c2VybmFtZRgEIAEoCRIOCgZwYXJvbGEYBSABKAki",
            "UAoJSW5zY3JpZXJlEgoKAmlkGAEgASgDEhUKDWlkUGFydGljaXBhbnQYAiAB",
            "KAMSDwoHaWRQcm9iYRgDIAEoAxIPCgdwdW5jdGFqGAQgASgDIjgKC1BhcnRp",
            "Y2lwYW50EgoKAmlkGAEgASgDEgwKBG51bWUYAiABKAkSDwoHcHJlbnVtZRgD",
            "IAEoCSJMCg5QYXJ0aWNpcGFudERUTxIKCgJpZBgBIAEoAxIMCgRudW1lGAIg",
            "ASgJEg8KB3ByZW51bWUYAyABKAkSDwoHcHVuY3RhahgEIAEoAyI5CgVQcm9i",
            "YRIKCgJpZBgBIAEoAxIRCgludW1lUHJvYmEYAiABKAkSEQoJaWRBcmJpdHJ1",
            "GAMgASgDIi4KCkFyYml0cnVEVE8SEAoIdXNlcm5hbWUYAiABKAkSDgoGcGFy",
            "b2xhGAMgASgJIu8DCg9UcmlhdGxvblJlcXVlc3QSNQoEdHlwZRgBIAEoDjIn",
            "LnRyaWF0bG9uLnByb3RvY29sLlRyaWF0bG9uUmVxdWVzdC5UeXBlEi0KB2Fy",
            "Yml0cnUYAiABKAsyGi50cmlhdGxvbi5wcm90b2NvbC5BcmJpdHJ1SAASMQoJ",
            "aW5zY3JpZXJlGAMgASgLMhwudHJpYXRsb24ucHJvdG9jb2wuSW5zY3JpZXJl",
            "SAASKQoFcHJvYmEYBCABKAsyGC50cmlhdGxvbi5wcm90b2NvbC5Qcm9iYUgA",
            "EjUKC3BhcnRpY2lwYW50GAUgASgLMh4udHJpYXRsb24ucHJvdG9jb2wuUGFy",
            "dGljaXBhbnRIABIzCgphcmJpdHJ1RFRPGAYgASgLMh0udHJpYXRsb24ucHJv",
            "dG9jb2wuQXJiaXRydURUT0gAIqABCgRUeXBlEgsKB1VOS05PV04QABIJCgVM",
            "T0dJThABEgoKBkxPR09VVBACEg8KC0dFVF9BUkJJVFJVEAMSEQoNQUREX0lO",
            "U0NSSUVSRRAEEg0KCUdFVF9QUk9CRRAFEh8KG0dFVF9QQVJUSUNJUEFOVElf",
            "Q1VfUFVOQ1RBShAGEiAKHEdFVF9QQVJUSUNJUEFOVElfREVfTEFfUFJPQkEQ",
            "B0IJCgdwYXlsb2FkItoEChBUcmlhdGxvblJlc3BvbnNlEjYKBHR5cGUYASAB",
            "KA4yKC50cmlhdGxvbi5wcm90b2NvbC5UcmlhdGxvblJlc3BvbnNlLlR5cGUS",
            "DQoFZXJyb3IYAiABKAkSKwoHYXJiaXRydRgDIAEoCzIaLnRyaWF0bG9uLnBy",
            "b3RvY29sLkFyYml0cnUSLwoJaW5zY3JpZXJpGAQgAygLMhwudHJpYXRsb24u",
            "cHJvdG9jb2wuSW5zY3JpZXJlEjoKD3BhcnRpY2lwYW50aURUTxgFIAMoCzIh",
            "LnRyaWF0bG9uLnByb3RvY29sLlBhcnRpY2lwYW50RFRPEicKBXByb2JlGAYg",
            "AygLMhgudHJpYXRsb24ucHJvdG9jb2wuUHJvYmESNAoMcGFydGljaXBhbnRp",
            "GAcgAygLMh4udHJpYXRsb24ucHJvdG9jb2wuUGFydGljaXBhbnQSLwoJaW5z",
            "Y3JpZXJlGAggASgLMhwudHJpYXRsb24ucHJvdG9jb2wuSW5zY3JpZXJlEjEK",
            "CmFyYml0cnVEVE8YCSABKAsyHS50cmlhdGxvbi5wcm90b2NvbC5BcmJpdHJ1",
            "RFRPIqEBCgRUeXBlEgsKB1VOS05PV04QABIGCgJPSxABEgkKBUVSUk9SEAIS",
            "EAoMVEFLRV9BUkJJVFJVEAMSDgoKVEFLRV9QUk9CRRAEEhIKDlVQREFURV9Q",
            "VU5DVEFKEAUSIAocVEFLRV9QQVJUSUNJUEFOVElfQ1VfUFVOQ1RBShAGEiEK",
            "HVRBS0VfUEFSVElDSVBBTlRJX0RFX0xBX1BST0JBEAdCJgoRcHJvdG9idWZm",
            "cHJvdG9jb2xCEVRyaWF0bG9uUHJvdG9idWZzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.Arbitru), global::Triatlon.Protocol.Arbitru.Parser, new[]{ "Id", "Nume", "Prenume", "Username", "Parola" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.Inscriere), global::Triatlon.Protocol.Inscriere.Parser, new[]{ "Id", "IdParticipant", "IdProba", "Punctaj" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.Participant), global::Triatlon.Protocol.Participant.Parser, new[]{ "Id", "Nume", "Prenume" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.ParticipantDTO), global::Triatlon.Protocol.ParticipantDTO.Parser, new[]{ "Id", "Nume", "Prenume", "Punctaj" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.Proba), global::Triatlon.Protocol.Proba.Parser, new[]{ "Id", "NumeProba", "IdArbitru" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.ArbitruDTO), global::Triatlon.Protocol.ArbitruDTO.Parser, new[]{ "Username", "Parola" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.TriatlonRequest), global::Triatlon.Protocol.TriatlonRequest.Parser, new[]{ "Type", "Arbitru", "Inscriere", "Proba", "Participant", "ArbitruDTO" }, new[]{ "Payload" }, new[]{ typeof(global::Triatlon.Protocol.TriatlonRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Triatlon.Protocol.TriatlonResponse), global::Triatlon.Protocol.TriatlonResponse.Parser, new[]{ "Type", "Error", "Arbitru", "Inscrieri", "ParticipantiDTO", "Probe", "Participanti", "Inscriere", "ArbitruDTO" }, null, new[]{ typeof(global::Triatlon.Protocol.TriatlonResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Arbitru : pb::IMessage<Arbitru>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Arbitru> _parser = new pb::MessageParser<Arbitru>(() => new Arbitru());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Arbitru> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Arbitru() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Arbitru(Arbitru other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      prenume_ = other.prenume_;
      username_ = other.username_;
      parola_ = other.parola_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Arbitru Clone() {
      return new Arbitru(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prenume" field.</summary>
    public const int PrenumeFieldNumber = 3;
    private string prenume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prenume {
      get { return prenume_; }
      set {
        prenume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 4;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parola" field.</summary>
    public const int ParolaFieldNumber = 5;
    private string parola_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Parola {
      get { return parola_; }
      set {
        parola_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Arbitru);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Arbitru other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Prenume != other.Prenume) return false;
      if (Username != other.Username) return false;
      if (Parola != other.Parola) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Prenume.Length != 0) hash ^= Prenume.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Parola.Length != 0) hash ^= Parola.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Prenume);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Prenume);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Prenume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prenume);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Parola.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parola);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Arbitru other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Prenume.Length != 0) {
        Prenume = other.Prenume;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Parola.Length != 0) {
        Parola = other.Parola;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Prenume = input.ReadString();
            break;
          }
          case 34: {
            Username = input.ReadString();
            break;
          }
          case 42: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Prenume = input.ReadString();
            break;
          }
          case 34: {
            Username = input.ReadString();
            break;
          }
          case 42: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Inscriere : pb::IMessage<Inscriere>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Inscriere> _parser = new pb::MessageParser<Inscriere>(() => new Inscriere());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Inscriere> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Inscriere() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Inscriere(Inscriere other) : this() {
      id_ = other.id_;
      idParticipant_ = other.idParticipant_;
      idProba_ = other.idProba_;
      punctaj_ = other.punctaj_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Inscriere Clone() {
      return new Inscriere(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "idParticipant" field.</summary>
    public const int IdParticipantFieldNumber = 2;
    private long idParticipant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdParticipant {
      get { return idParticipant_; }
      set {
        idParticipant_ = value;
      }
    }

    /// <summary>Field number for the "idProba" field.</summary>
    public const int IdProbaFieldNumber = 3;
    private long idProba_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdProba {
      get { return idProba_; }
      set {
        idProba_ = value;
      }
    }

    /// <summary>Field number for the "punctaj" field.</summary>
    public const int PunctajFieldNumber = 4;
    private long punctaj_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Punctaj {
      get { return punctaj_; }
      set {
        punctaj_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Inscriere);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Inscriere other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (IdParticipant != other.IdParticipant) return false;
      if (IdProba != other.IdProba) return false;
      if (Punctaj != other.Punctaj) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (IdParticipant != 0L) hash ^= IdParticipant.GetHashCode();
      if (IdProba != 0L) hash ^= IdProba.GetHashCode();
      if (Punctaj != 0L) hash ^= Punctaj.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (IdParticipant != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdParticipant);
      }
      if (IdProba != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(IdProba);
      }
      if (Punctaj != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Punctaj);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (IdParticipant != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdParticipant);
      }
      if (IdProba != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(IdProba);
      }
      if (Punctaj != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Punctaj);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (IdParticipant != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdParticipant);
      }
      if (IdProba != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdProba);
      }
      if (Punctaj != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Punctaj);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Inscriere other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.IdParticipant != 0L) {
        IdParticipant = other.IdParticipant;
      }
      if (other.IdProba != 0L) {
        IdProba = other.IdProba;
      }
      if (other.Punctaj != 0L) {
        Punctaj = other.Punctaj;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            IdParticipant = input.ReadInt64();
            break;
          }
          case 24: {
            IdProba = input.ReadInt64();
            break;
          }
          case 32: {
            Punctaj = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            IdParticipant = input.ReadInt64();
            break;
          }
          case 24: {
            IdProba = input.ReadInt64();
            break;
          }
          case 32: {
            Punctaj = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Participant : pb::IMessage<Participant>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Participant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant(Participant other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      prenume_ = other.prenume_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant Clone() {
      return new Participant(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prenume" field.</summary>
    public const int PrenumeFieldNumber = 3;
    private string prenume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prenume {
      get { return prenume_; }
      set {
        prenume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Participant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Participant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Prenume != other.Prenume) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Prenume.Length != 0) hash ^= Prenume.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Prenume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Prenume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Prenume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prenume);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Participant other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Prenume.Length != 0) {
        Prenume = other.Prenume;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Prenume = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Prenume = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ParticipantDTO : pb::IMessage<ParticipantDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParticipantDTO> _parser = new pb::MessageParser<ParticipantDTO>(() => new ParticipantDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParticipantDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantDTO(ParticipantDTO other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      prenume_ = other.prenume_;
      punctaj_ = other.punctaj_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantDTO Clone() {
      return new ParticipantDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prenume" field.</summary>
    public const int PrenumeFieldNumber = 3;
    private string prenume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prenume {
      get { return prenume_; }
      set {
        prenume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "punctaj" field.</summary>
    public const int PunctajFieldNumber = 4;
    private long punctaj_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Punctaj {
      get { return punctaj_; }
      set {
        punctaj_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParticipantDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParticipantDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Prenume != other.Prenume) return false;
      if (Punctaj != other.Punctaj) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Prenume.Length != 0) hash ^= Prenume.GetHashCode();
      if (Punctaj != 0L) hash ^= Punctaj.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Prenume);
      }
      if (Punctaj != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Punctaj);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Prenume.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Prenume);
      }
      if (Punctaj != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Punctaj);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Prenume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prenume);
      }
      if (Punctaj != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Punctaj);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParticipantDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Prenume.Length != 0) {
        Prenume = other.Prenume;
      }
      if (other.Punctaj != 0L) {
        Punctaj = other.Punctaj;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Prenume = input.ReadString();
            break;
          }
          case 32: {
            Punctaj = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Prenume = input.ReadString();
            break;
          }
          case 32: {
            Punctaj = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Proba : pb::IMessage<Proba>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Proba> _parser = new pb::MessageParser<Proba>(() => new Proba());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Proba> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba(Proba other) : this() {
      id_ = other.id_;
      numeProba_ = other.numeProba_;
      idArbitru_ = other.idArbitru_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba Clone() {
      return new Proba(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "numeProba" field.</summary>
    public const int NumeProbaFieldNumber = 2;
    private string numeProba_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeProba {
      get { return numeProba_; }
      set {
        numeProba_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "idArbitru" field.</summary>
    public const int IdArbitruFieldNumber = 3;
    private long idArbitru_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdArbitru {
      get { return idArbitru_; }
      set {
        idArbitru_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Proba);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Proba other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NumeProba != other.NumeProba) return false;
      if (IdArbitru != other.IdArbitru) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (NumeProba.Length != 0) hash ^= NumeProba.GetHashCode();
      if (IdArbitru != 0L) hash ^= IdArbitru.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (NumeProba.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeProba);
      }
      if (IdArbitru != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(IdArbitru);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (NumeProba.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeProba);
      }
      if (IdArbitru != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(IdArbitru);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (NumeProba.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeProba);
      }
      if (IdArbitru != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdArbitru);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Proba other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.NumeProba.Length != 0) {
        NumeProba = other.NumeProba;
      }
      if (other.IdArbitru != 0L) {
        IdArbitru = other.IdArbitru;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            NumeProba = input.ReadString();
            break;
          }
          case 24: {
            IdArbitru = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            NumeProba = input.ReadString();
            break;
          }
          case 24: {
            IdArbitru = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ArbitruDTO : pb::IMessage<ArbitruDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ArbitruDTO> _parser = new pb::MessageParser<ArbitruDTO>(() => new ArbitruDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ArbitruDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArbitruDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArbitruDTO(ArbitruDTO other) : this() {
      username_ = other.username_;
      parola_ = other.parola_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ArbitruDTO Clone() {
      return new ArbitruDTO(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parola" field.</summary>
    public const int ParolaFieldNumber = 3;
    private string parola_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Parola {
      get { return parola_; }
      set {
        parola_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ArbitruDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ArbitruDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Parola != other.Parola) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Parola.Length != 0) hash ^= Parola.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Parola.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parola);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ArbitruDTO other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Parola.Length != 0) {
        Parola = other.Parola;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TriatlonRequest : pb::IMessage<TriatlonRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TriatlonRequest> _parser = new pb::MessageParser<TriatlonRequest>(() => new TriatlonRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TriatlonRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriatlonRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriatlonRequest(TriatlonRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Arbitru:
          Arbitru = other.Arbitru.Clone();
          break;
        case PayloadOneofCase.Inscriere:
          Inscriere = other.Inscriere.Clone();
          break;
        case PayloadOneofCase.Proba:
          Proba = other.Proba.Clone();
          break;
        case PayloadOneofCase.Participant:
          Participant = other.Participant.Clone();
          break;
        case PayloadOneofCase.ArbitruDTO:
          ArbitruDTO = other.ArbitruDTO.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriatlonRequest Clone() {
      return new TriatlonRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Triatlon.Protocol.TriatlonRequest.Types.Type type_ = global::Triatlon.Protocol.TriatlonRequest.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.TriatlonRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "arbitru" field.</summary>
    public const int ArbitruFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.Arbitru Arbitru {
      get { return payloadCase_ == PayloadOneofCase.Arbitru ? (global::Triatlon.Protocol.Arbitru) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Arbitru;
      }
    }

    /// <summary>Field number for the "inscriere" field.</summary>
    public const int InscriereFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.Inscriere Inscriere {
      get { return payloadCase_ == PayloadOneofCase.Inscriere ? (global::Triatlon.Protocol.Inscriere) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Inscriere;
      }
    }

    /// <summary>Field number for the "proba" field.</summary>
    public const int ProbaFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.Proba Proba {
      get { return payloadCase_ == PayloadOneofCase.Proba ? (global::Triatlon.Protocol.Proba) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Proba;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.Participant Participant {
      get { return payloadCase_ == PayloadOneofCase.Participant ? (global::Triatlon.Protocol.Participant) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Participant;
      }
    }

    /// <summary>Field number for the "arbitruDTO" field.</summary>
    public const int ArbitruDTOFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.ArbitruDTO ArbitruDTO {
      get { return payloadCase_ == PayloadOneofCase.ArbitruDTO ? (global::Triatlon.Protocol.ArbitruDTO) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ArbitruDTO;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Arbitru = 2,
      Inscriere = 3,
      Proba = 4,
      Participant = 5,
      ArbitruDTO = 6,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TriatlonRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TriatlonRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Arbitru, other.Arbitru)) return false;
      if (!object.Equals(Inscriere, other.Inscriere)) return false;
      if (!object.Equals(Proba, other.Proba)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(ArbitruDTO, other.ArbitruDTO)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Triatlon.Protocol.TriatlonRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Arbitru) hash ^= Arbitru.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Inscriere) hash ^= Inscriere.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Proba) hash ^= Proba.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Participant) hash ^= Participant.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ArbitruDTO) hash ^= ArbitruDTO.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Triatlon.Protocol.TriatlonRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Arbitru) {
        output.WriteRawTag(18);
        output.WriteMessage(Arbitru);
      }
      if (payloadCase_ == PayloadOneofCase.Inscriere) {
        output.WriteRawTag(26);
        output.WriteMessage(Inscriere);
      }
      if (payloadCase_ == PayloadOneofCase.Proba) {
        output.WriteRawTag(34);
        output.WriteMessage(Proba);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(42);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.ArbitruDTO) {
        output.WriteRawTag(50);
        output.WriteMessage(ArbitruDTO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Triatlon.Protocol.TriatlonRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Arbitru) {
        output.WriteRawTag(18);
        output.WriteMessage(Arbitru);
      }
      if (payloadCase_ == PayloadOneofCase.Inscriere) {
        output.WriteRawTag(26);
        output.WriteMessage(Inscriere);
      }
      if (payloadCase_ == PayloadOneofCase.Proba) {
        output.WriteRawTag(34);
        output.WriteMessage(Proba);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(42);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.ArbitruDTO) {
        output.WriteRawTag(50);
        output.WriteMessage(ArbitruDTO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Triatlon.Protocol.TriatlonRequest.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Arbitru) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Arbitru);
      }
      if (payloadCase_ == PayloadOneofCase.Inscriere) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Inscriere);
      }
      if (payloadCase_ == PayloadOneofCase.Proba) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Proba);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.ArbitruDTO) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArbitruDTO);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TriatlonRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Triatlon.Protocol.TriatlonRequest.Types.Type.Unknown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Arbitru:
          if (Arbitru == null) {
            Arbitru = new global::Triatlon.Protocol.Arbitru();
          }
          Arbitru.MergeFrom(other.Arbitru);
          break;
        case PayloadOneofCase.Inscriere:
          if (Inscriere == null) {
            Inscriere = new global::Triatlon.Protocol.Inscriere();
          }
          Inscriere.MergeFrom(other.Inscriere);
          break;
        case PayloadOneofCase.Proba:
          if (Proba == null) {
            Proba = new global::Triatlon.Protocol.Proba();
          }
          Proba.MergeFrom(other.Proba);
          break;
        case PayloadOneofCase.Participant:
          if (Participant == null) {
            Participant = new global::Triatlon.Protocol.Participant();
          }
          Participant.MergeFrom(other.Participant);
          break;
        case PayloadOneofCase.ArbitruDTO:
          if (ArbitruDTO == null) {
            ArbitruDTO = new global::Triatlon.Protocol.ArbitruDTO();
          }
          ArbitruDTO.MergeFrom(other.ArbitruDTO);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Triatlon.Protocol.TriatlonRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Triatlon.Protocol.Arbitru subBuilder = new global::Triatlon.Protocol.Arbitru();
            if (payloadCase_ == PayloadOneofCase.Arbitru) {
              subBuilder.MergeFrom(Arbitru);
            }
            input.ReadMessage(subBuilder);
            Arbitru = subBuilder;
            break;
          }
          case 26: {
            global::Triatlon.Protocol.Inscriere subBuilder = new global::Triatlon.Protocol.Inscriere();
            if (payloadCase_ == PayloadOneofCase.Inscriere) {
              subBuilder.MergeFrom(Inscriere);
            }
            input.ReadMessage(subBuilder);
            Inscriere = subBuilder;
            break;
          }
          case 34: {
            global::Triatlon.Protocol.Proba subBuilder = new global::Triatlon.Protocol.Proba();
            if (payloadCase_ == PayloadOneofCase.Proba) {
              subBuilder.MergeFrom(Proba);
            }
            input.ReadMessage(subBuilder);
            Proba = subBuilder;
            break;
          }
          case 42: {
            global::Triatlon.Protocol.Participant subBuilder = new global::Triatlon.Protocol.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 50: {
            global::Triatlon.Protocol.ArbitruDTO subBuilder = new global::Triatlon.Protocol.ArbitruDTO();
            if (payloadCase_ == PayloadOneofCase.ArbitruDTO) {
              subBuilder.MergeFrom(ArbitruDTO);
            }
            input.ReadMessage(subBuilder);
            ArbitruDTO = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Triatlon.Protocol.TriatlonRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Triatlon.Protocol.Arbitru subBuilder = new global::Triatlon.Protocol.Arbitru();
            if (payloadCase_ == PayloadOneofCase.Arbitru) {
              subBuilder.MergeFrom(Arbitru);
            }
            input.ReadMessage(subBuilder);
            Arbitru = subBuilder;
            break;
          }
          case 26: {
            global::Triatlon.Protocol.Inscriere subBuilder = new global::Triatlon.Protocol.Inscriere();
            if (payloadCase_ == PayloadOneofCase.Inscriere) {
              subBuilder.MergeFrom(Inscriere);
            }
            input.ReadMessage(subBuilder);
            Inscriere = subBuilder;
            break;
          }
          case 34: {
            global::Triatlon.Protocol.Proba subBuilder = new global::Triatlon.Protocol.Proba();
            if (payloadCase_ == PayloadOneofCase.Proba) {
              subBuilder.MergeFrom(Proba);
            }
            input.ReadMessage(subBuilder);
            Proba = subBuilder;
            break;
          }
          case 42: {
            global::Triatlon.Protocol.Participant subBuilder = new global::Triatlon.Protocol.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 50: {
            global::Triatlon.Protocol.ArbitruDTO subBuilder = new global::Triatlon.Protocol.ArbitruDTO();
            if (payloadCase_ == PayloadOneofCase.ArbitruDTO) {
              subBuilder.MergeFrom(ArbitruDTO);
            }
            input.ReadMessage(subBuilder);
            ArbitruDTO = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TriatlonRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("LOGIN")] Login = 1,
        [pbr::OriginalName("LOGOUT")] Logout = 2,
        [pbr::OriginalName("GET_ARBITRU")] GetArbitru = 3,
        [pbr::OriginalName("ADD_INSCRIERE")] AddInscriere = 4,
        [pbr::OriginalName("GET_PROBE")] GetProbe = 5,
        [pbr::OriginalName("GET_PARTICIPANTI_CU_PUNCTAJ")] GetParticipantiCuPunctaj = 6,
        [pbr::OriginalName("GET_PARTICIPANTI_DE_LA_PROBA")] GetParticipantiDeLaProba = 7,
      }

    }
    #endregion

  }

  public sealed partial class TriatlonResponse : pb::IMessage<TriatlonResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TriatlonResponse> _parser = new pb::MessageParser<TriatlonResponse>(() => new TriatlonResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TriatlonResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Triatlon.Protocol.TriatlonProtocolV3Reflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriatlonResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriatlonResponse(TriatlonResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      arbitru_ = other.arbitru_ != null ? other.arbitru_.Clone() : null;
      inscrieri_ = other.inscrieri_.Clone();
      participantiDTO_ = other.participantiDTO_.Clone();
      probe_ = other.probe_.Clone();
      participanti_ = other.participanti_.Clone();
      inscriere_ = other.inscriere_ != null ? other.inscriere_.Clone() : null;
      arbitruDTO_ = other.arbitruDTO_ != null ? other.arbitruDTO_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TriatlonResponse Clone() {
      return new TriatlonResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Triatlon.Protocol.TriatlonResponse.Types.Type type_ = global::Triatlon.Protocol.TriatlonResponse.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.TriatlonResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "arbitru" field.</summary>
    public const int ArbitruFieldNumber = 3;
    private global::Triatlon.Protocol.Arbitru arbitru_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.Arbitru Arbitru {
      get { return arbitru_; }
      set {
        arbitru_ = value;
      }
    }

    /// <summary>Field number for the "inscrieri" field.</summary>
    public const int InscrieriFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Triatlon.Protocol.Inscriere> _repeated_inscrieri_codec
        = pb::FieldCodec.ForMessage(34, global::Triatlon.Protocol.Inscriere.Parser);
    private readonly pbc::RepeatedField<global::Triatlon.Protocol.Inscriere> inscrieri_ = new pbc::RepeatedField<global::Triatlon.Protocol.Inscriere>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Triatlon.Protocol.Inscriere> Inscrieri {
      get { return inscrieri_; }
    }

    /// <summary>Field number for the "participantiDTO" field.</summary>
    public const int ParticipantiDTOFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Triatlon.Protocol.ParticipantDTO> _repeated_participantiDTO_codec
        = pb::FieldCodec.ForMessage(42, global::Triatlon.Protocol.ParticipantDTO.Parser);
    private readonly pbc::RepeatedField<global::Triatlon.Protocol.ParticipantDTO> participantiDTO_ = new pbc::RepeatedField<global::Triatlon.Protocol.ParticipantDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Triatlon.Protocol.ParticipantDTO> ParticipantiDTO {
      get { return participantiDTO_; }
    }

    /// <summary>Field number for the "probe" field.</summary>
    public const int ProbeFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Triatlon.Protocol.Proba> _repeated_probe_codec
        = pb::FieldCodec.ForMessage(50, global::Triatlon.Protocol.Proba.Parser);
    private readonly pbc::RepeatedField<global::Triatlon.Protocol.Proba> probe_ = new pbc::RepeatedField<global::Triatlon.Protocol.Proba>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Triatlon.Protocol.Proba> Probe {
      get { return probe_; }
    }

    /// <summary>Field number for the "participanti" field.</summary>
    public const int ParticipantiFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Triatlon.Protocol.Participant> _repeated_participanti_codec
        = pb::FieldCodec.ForMessage(58, global::Triatlon.Protocol.Participant.Parser);
    private readonly pbc::RepeatedField<global::Triatlon.Protocol.Participant> participanti_ = new pbc::RepeatedField<global::Triatlon.Protocol.Participant>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Triatlon.Protocol.Participant> Participanti {
      get { return participanti_; }
    }

    /// <summary>Field number for the "inscriere" field.</summary>
    public const int InscriereFieldNumber = 8;
    private global::Triatlon.Protocol.Inscriere inscriere_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.Inscriere Inscriere {
      get { return inscriere_; }
      set {
        inscriere_ = value;
      }
    }

    /// <summary>Field number for the "arbitruDTO" field.</summary>
    public const int ArbitruDTOFieldNumber = 9;
    private global::Triatlon.Protocol.ArbitruDTO arbitruDTO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Triatlon.Protocol.ArbitruDTO ArbitruDTO {
      get { return arbitruDTO_; }
      set {
        arbitruDTO_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TriatlonResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TriatlonResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Arbitru, other.Arbitru)) return false;
      if(!inscrieri_.Equals(other.inscrieri_)) return false;
      if(!participantiDTO_.Equals(other.participantiDTO_)) return false;
      if(!probe_.Equals(other.probe_)) return false;
      if(!participanti_.Equals(other.participanti_)) return false;
      if (!object.Equals(Inscriere, other.Inscriere)) return false;
      if (!object.Equals(ArbitruDTO, other.ArbitruDTO)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Triatlon.Protocol.TriatlonResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (arbitru_ != null) hash ^= Arbitru.GetHashCode();
      hash ^= inscrieri_.GetHashCode();
      hash ^= participantiDTO_.GetHashCode();
      hash ^= probe_.GetHashCode();
      hash ^= participanti_.GetHashCode();
      if (inscriere_ != null) hash ^= Inscriere.GetHashCode();
      if (arbitruDTO_ != null) hash ^= ArbitruDTO.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Triatlon.Protocol.TriatlonResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (arbitru_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Arbitru);
      }
      inscrieri_.WriteTo(output, _repeated_inscrieri_codec);
      participantiDTO_.WriteTo(output, _repeated_participantiDTO_codec);
      probe_.WriteTo(output, _repeated_probe_codec);
      participanti_.WriteTo(output, _repeated_participanti_codec);
      if (inscriere_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Inscriere);
      }
      if (arbitruDTO_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ArbitruDTO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Triatlon.Protocol.TriatlonResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (arbitru_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Arbitru);
      }
      inscrieri_.WriteTo(ref output, _repeated_inscrieri_codec);
      participantiDTO_.WriteTo(ref output, _repeated_participantiDTO_codec);
      probe_.WriteTo(ref output, _repeated_probe_codec);
      participanti_.WriteTo(ref output, _repeated_participanti_codec);
      if (inscriere_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Inscriere);
      }
      if (arbitruDTO_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ArbitruDTO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Triatlon.Protocol.TriatlonResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (arbitru_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Arbitru);
      }
      size += inscrieri_.CalculateSize(_repeated_inscrieri_codec);
      size += participantiDTO_.CalculateSize(_repeated_participantiDTO_codec);
      size += probe_.CalculateSize(_repeated_probe_codec);
      size += participanti_.CalculateSize(_repeated_participanti_codec);
      if (inscriere_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Inscriere);
      }
      if (arbitruDTO_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArbitruDTO);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TriatlonResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Triatlon.Protocol.TriatlonResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.arbitru_ != null) {
        if (arbitru_ == null) {
          Arbitru = new global::Triatlon.Protocol.Arbitru();
        }
        Arbitru.MergeFrom(other.Arbitru);
      }
      inscrieri_.Add(other.inscrieri_);
      participantiDTO_.Add(other.participantiDTO_);
      probe_.Add(other.probe_);
      participanti_.Add(other.participanti_);
      if (other.inscriere_ != null) {
        if (inscriere_ == null) {
          Inscriere = new global::Triatlon.Protocol.Inscriere();
        }
        Inscriere.MergeFrom(other.Inscriere);
      }
      if (other.arbitruDTO_ != null) {
        if (arbitruDTO_ == null) {
          ArbitruDTO = new global::Triatlon.Protocol.ArbitruDTO();
        }
        ArbitruDTO.MergeFrom(other.ArbitruDTO);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Triatlon.Protocol.TriatlonResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (arbitru_ == null) {
              Arbitru = new global::Triatlon.Protocol.Arbitru();
            }
            input.ReadMessage(Arbitru);
            break;
          }
          case 34: {
            inscrieri_.AddEntriesFrom(input, _repeated_inscrieri_codec);
            break;
          }
          case 42: {
            participantiDTO_.AddEntriesFrom(input, _repeated_participantiDTO_codec);
            break;
          }
          case 50: {
            probe_.AddEntriesFrom(input, _repeated_probe_codec);
            break;
          }
          case 58: {
            participanti_.AddEntriesFrom(input, _repeated_participanti_codec);
            break;
          }
          case 66: {
            if (inscriere_ == null) {
              Inscriere = new global::Triatlon.Protocol.Inscriere();
            }
            input.ReadMessage(Inscriere);
            break;
          }
          case 74: {
            if (arbitruDTO_ == null) {
              ArbitruDTO = new global::Triatlon.Protocol.ArbitruDTO();
            }
            input.ReadMessage(ArbitruDTO);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Triatlon.Protocol.TriatlonResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (arbitru_ == null) {
              Arbitru = new global::Triatlon.Protocol.Arbitru();
            }
            input.ReadMessage(Arbitru);
            break;
          }
          case 34: {
            inscrieri_.AddEntriesFrom(ref input, _repeated_inscrieri_codec);
            break;
          }
          case 42: {
            participantiDTO_.AddEntriesFrom(ref input, _repeated_participantiDTO_codec);
            break;
          }
          case 50: {
            probe_.AddEntriesFrom(ref input, _repeated_probe_codec);
            break;
          }
          case 58: {
            participanti_.AddEntriesFrom(ref input, _repeated_participanti_codec);
            break;
          }
          case 66: {
            if (inscriere_ == null) {
              Inscriere = new global::Triatlon.Protocol.Inscriere();
            }
            input.ReadMessage(Inscriere);
            break;
          }
          case 74: {
            if (arbitruDTO_ == null) {
              ArbitruDTO = new global::Triatlon.Protocol.ArbitruDTO();
            }
            input.ReadMessage(ArbitruDTO);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TriatlonResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("OK")] Ok = 1,
        [pbr::OriginalName("ERROR")] Error = 2,
        [pbr::OriginalName("TAKE_ARBITRU")] TakeArbitru = 3,
        [pbr::OriginalName("TAKE_PROBE")] TakeProbe = 4,
        [pbr::OriginalName("UPDATE_PUNCTAJ")] UpdatePunctaj = 5,
        [pbr::OriginalName("TAKE_PARTICIPANTI_CU_PUNCTAJ")] TakeParticipantiCuPunctaj = 6,
        [pbr::OriginalName("TAKE_PARTICIPANTI_DE_LA_PROBA")] TakeParticipantiDeLaProba = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
